logo: "/assets/images/consynsys.svg"
title: ConSynSys Environment Dashboard
description: Centralized dashboard for accessing customer environments.
baseurl: "/customer-dashboard"
url: "https://tsmithconsynsys.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
minimal_mistakes_skin: "dark"
